spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://localhost:3306/devopsBoard?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${database_user}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080
