spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://35.225.87.247:3306/devopsBoard?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: test
    password: 0000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080
