spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://10.182.0.2:3307/devopsBoard?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080
