
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    # 이게 ssh username@ip

    - name: Set Gradle Wrapper executable permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build --info --stacktrace
      
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Docker build
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO}} .

    - name: Docker push
      run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO}}
    
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD }}
        script: |
          docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO}} 
          docker rm -f ${{secrets.DOCKER_REPO}} 
          docker run --name ${{secrets.DOCKER_REPO}} -p 8080:8080 -e profiles=prod -e username=root -e password=1q2w3e4r --network server -d ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPO}}

    
